### ISSUE TITLE
Error installing slowmoVideo AppImage v0.6

### ISSUE THREAD

**Issue by lfom** [vinifmor/bauh#132]
**Describe the bug**
1. Download latest version from http://slowmovideo.granjow.net/download.html
2. Try to install the downloaded AppImage file, bauh crashes but nothing is actually installed (error log from running bauh from CLI below)

**Software Environment**
bauh version: 0.9.6
O.S: Manjaro 20.0.3
Python version: 3.8.3
bauh installation method: pamac-manager (GUI)

I would suggest that the original download file is deleted only after the whole process is successful, and also maybe it is a good idea to check for failed process and do a "cleanup" once bauh is restarted. It seems that the error is caused because bauh cannot find the icon used for app for some reason...

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 941, in run
    success = self.manager.execute_custom_action(action=self.custom_action,
  File "/usr/lib/python3.8/site-packages/bauh/view/core/controller.py", line 492, in execute_custom_action
    return eval('man.{}({}root_password=root_password, watcher=watcher)'.format(action.manager_method, 'pkg=pkg, ' if pkg else ''))
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 113, in install_file
    res = self.install(root_password=root_password, pkg=appim, disk_loader=None, watcher=watcher).success
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 507, in install
    shutil.copy('{}/{}'.format(extracted_folder, extracted_icon), icon_path)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/lfom/.local/share/bauh/appimage/installed/slowmoui/squashfs-root/AppIcon.png'
Fatal Python error: Aborted

Current thread 0x00007f71977fe700 (most recent call first):
<no Python frame>

Thread 0x00007f7177fff700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 728 in run

Thread 0x00007f71777fe700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/prepare.py", line 114 in run

Thread 0x00007f7176ffd700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 728 in run

Thread 0x00007f71967fc700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/worker.py", line 106 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f7197fff700 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/view/util/cache.py", line 95 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f71c1da5740 (most recent call first):
  File "/usr/lib/python3.8/site-packages/bauh/app.py", line 51 in main
  File "/usr/bin/bauh", line 33 in <module>

```

**Comment by vinifmor** [comment]
@lfom , I'm going to check here. Thanks for letting me know.

**Comment by vinifmor** [comment]
@lfom , I've fixed this issue on the staging branch. Could you give me a feedback if its working on your end ? (you can install it through AUR as **bauh-staging** -> 0.9.7.RC-3)
![appimage_fix](https://user-images.githubusercontent.com/4312414/89951932-af75ce00-dc02-11ea-8cf7-8d44a5a64b08.png)

**Comment by lfom** [comment]
Sorry for the delay, but I don't have access to the same machine as of now. I can test with another installation once the new version is released so the bug can be closed.
Regards
