### ISSUE TITLE
Bauh not starting

### ISSUE THREAD

**Issue by nigelwarning** [vinifmor/bauh#146]
**Describe the bug**
I installed bauh from the AUR, also tried bauh-staging, but both have some problems. Bauh won't open when you start it.
When you try running it from terminal it returns:

`Traceback (most recent call last):
  File "/usr/bin/bauh", line 33, in <module>
    sys.exit(load_entry_point('bauh==0.9.8', 'console_scripts', 'bauh')())
  File "/usr/bin/bauh", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: bauh
`

**Software Environment**
bauh version: 0.9.8-1
O.S: name and version: Arch
Python version: 3.9
Installation method: Yay AUR

**Comment by nigelwarning** [comment]
Fixed it. I enabled the chaotic-aur and in that one it doesnt work. The AUR standalone version does work.
