### ISSUE TITLE
undefined symbol: _ZdlPvm, version Qt_5

### ISSUE THREAD

**Issue by arteze** [vinifmor/bauh#178]
I have the following error when running bauh:

```sh
root@puppypc30690:~# bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib/python3.9/site-packages/bauh/app.py", line 7, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```
Python 3.9.5

How do I solve it?

**Comment by arteze** [comment]
I have managed to overcome that problem, but now I have another error:

```sh
root@puppypc30690:~# bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/bauh/app.py", line 50, in main
    from bauh.manage import new_manage_panel
  File "/usr/lib/python3.9/site-packages/bauh/manage.py", line 5, in <module>
    from PyQt5.QtWidgets import QApplication, QWidget
ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5
```

**Comment by vinifmor** [comment]
Hi @arteze , it seems something related to your OS Qt 5 packages. I've never seen such error before.

**Comment by arteze** [comment]
Exactly, in particular it seems to be some Qt5 Open GL plugin.

Is it totally necessary that bauh require `QtGui.abi3.so`? i can import Qt5 submodules and avoid their use?

**Comment by arteze** [comment]
I've reinstalled bauh again, this time in another PuppyLinux session, but now I'm getting another error.

```sh
root@puppypc30690:/initrd/mnt/dev_save/lk/Python-3.9.5# bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib64/python3.5/site-packages/bauh/app.py", line 7, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
ImportError: /usr/lib64/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: undefined symbol: ucal_clone_56
root@puppypc30690:/initrd/mnt/dev_save/lk/Python-3.9.5# bauh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 5, in <module>
    from bauh.app import main
  File "/usr/lib64/python3.5/site-packages/bauh/app.py", line 7, in <module>
    from PyQt5.QtCore import QCoreApplication, Qt
ImportError: /usr/lib64/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: undefined symbol: ucal_clone_56
```

Python 3.5.1

**Comment by arteze** [comment]
Again I was able to fix the above error. What I did was install `icu`... But another appears:

```sh
Traceback (most recent call last):
  File "/usr/bin/bauh", line 8, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.5/site-packages/bauh/app.py", line 50, in main
    from bauh.manage import new_manage_panel
  File "/usr/lib64/python3.5/site-packages/bauh/manage.py", line 8, in <module>
    from bauh.api.abstract.context import ApplicationContext
  File "/usr/lib64/python3.5/site-packages/bauh/api/abstract/context.py", line 5, in <module>
    from bauh.api.abstract.disk import DiskCacheLoaderFactory
  File "/usr/lib64/python3.5/site-packages/bauh/api/abstract/disk.py", line 2, in <module>
    from typing import Type
ImportError: cannot import name 'Type'
```

**Comment by arteze** [comment]
I have returned to the initial error:

```sh
ImportError: /usr/local/lib/python3.9/dist-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```

**Comment by vinifmor** [comment]
Odd errors. You could post them in your distro forum to see if someone can give you a hand on that. I haven't got any issues with Arch and Ubuntu Qt5 packages.

**Comment by arteze** [comment]
Well, I had another problem, which did not recognize the XCB plugin, when I wanted to fix it, I put on my black screen and I could not do anything else.

**Comment by vinifmor** [comment]
You can try the [isolated installation](https://github.com/vinifmor/bauh#inst_iso) to see if these issues don't happen

**Comment by arteze** [comment]
It worked perfectly ... The only problem was that I had to hex edit the following file.

`/root/bauh_env/lib/python3.9/site-packages/PyQt5/Qt5/lib/libQt5Core.so.5`

I have changed all the strings `_56` to `_67` to suit the version of Unicode I have.

![Screenshot(44)](https://user-images.githubusercontent.com/3245767/118295564-881e9b00-b4cb-11eb-8944-6312cb589de8.png)

With that it works perfect for me, I leave the screenshot.

**Comment by vinifmor** [comment]
Great. I'm going to let the issue open so other people can follow your steps
