### ISSUE TITLE
bauh-staging 0.9.23.RC-4 on archlinux disappear after refresh apps !!!

### ISSUE THREAD

**Issue by LeBron7077** [vinifmor/bauh#216]
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 702, in _finish_refresh_packages
    if self.update_pkgs(res['installed'], as_installed=as_installed, types=res['types']):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 964, in update_pkgs
    self._update_table(pkgs_info=pkgs_info)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 842, in _update_table
    self._resize(accept_lower_width=len(self.pkgs) > 0)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 1079, in _resize
    self.resize(new_width, self.height())
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
Fatal Python error: Aborted

Thread 0x00007fab3effd640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/thread.py", line 822 in run

Thread 0x00007fab3dffb640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007fab513a7640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/util/cache.py", line 96 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007fab6b8e3740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/app.py", line 57 in main
  File "/usr/bin/bauh", line 33 in <module>

Extension modules: PyQt5.QtCore, yaml._yaml, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork (total: 5)
Aborted (core dumped)

**Comment by vinifmor** [comment]
@LeBron7077 , it seems to be something related to your QT libraries bases on the lines below:
```
self.resize(new_width, self.height())
TypeError: arguments did not match any overloaded call:
resize(self, QSize): argument 1 has unexpected type 'float'
resize(self, int, int): argument 1 has unexpected type 'float'
```

I'm going to have a look here if it is possible to force an "int" cast. Thanks for reporting.

**Comment by LeBron7077** [comment]
Hello DEV,
How can I fix that on arch, Just so you know, I'm not an expert 
Thanks for the quick reply,

**Comment by vinifmor** [comment]
@LeBron7077 I've just pushed a possible fix on the **staging** branch. Could you try reinstalling it from AUR and give me a feedback if the issue has been fixed ?

**Comment by LeBron7077** [comment]
It,s work, after reinstalling bauh-staging-0.9.24.RC-1 everything fine,😊
Thank you so so much, for your quick response.. You are a great & genius DEV,🔥🙏

**Comment by LeBron7077** [comment]
actually, I love it dude,🤎
again,Thanks for your effort .
