### ISSUE TITLE
another bug bauh-staging 0.9.24.RC-1 on archlinux disappear after click settings !!!

### ISSUE THREAD

**Issue by LeBron7077** [vinifmor/bauh#217]
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 1479, in show_settings
    self.settings_window = SettingsWindow(self.manager, self.i18n, self.screen_size, self)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/settings.py", line 50, in __init__
    self.tab_group = to_widget(self.settings_model, i18n)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 979, in to_widget
    return TabGroupQt(comp, i18n, parent)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 941, in __init__
    scroll.setWidget(to_widget(c.content, i18n))
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 981, in to_widget
    return PanelQt(comp, i18n, parent)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 699, in __init__
    self.layout().addWidget(to_widget(c, i18n))
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 977, in to_widget
    return FormQt(comp, i18n)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 724, in __init__
    field = self._wrap(self._new_range_input(c), c)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/components.py", line 842, in _new_range_input
    spinner.setValue(model.value if model.value is not None else model.min)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
Fatal Python error: Aborted

Thread 0x00007f87227fc640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/thread.py", line 822 in run

Thread 0x00007f8723fff640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007f872d5ca640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/util/cache.py", line 96 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f874bbc1740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/app.py", line 57 in main
  File "/usr/bin/bauh", line 33 in <module>

Extension modules: PyQt5.QtCore, yaml._yaml, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork (total: 5)
Aborted (core dumped)

🙈🙈

**Comment by vinifmor** [comment]
Same issue on a different file. I'm going to publish a fix ASAP.

**Comment by LeBron7077** [comment]
🙈🙈
yes, yes it works well on bauh-staging-0.9.24.RC-2, 
you are the fastest developer I know so far, thanks for that, and another thanks for the speed of response, and for this great apps😊🤎

**Comment by vinifmor** [comment]
Great. Let me know if any issue pops up again.

**Comment by LeBron7077** [comment]
- [ ] Roger that,🙈🙈
