### ISSUE TITLE
Is there a compatibility with a Python 3.10?

### ISSUE THREAD

**Issue by kpspu** [vinifmor/bauh#218]
Hi there!
I am a newbie for a Linux, so do not judge me severely if I posted a wrong issue.
So the problem is that after installing new system update on EndeavourOS I couldn't open bauh anymore.
There are an article: https://forum.endeavouros.com/t/brief-psa-python-3-10-just-released/21219

Is there a possibility this might be an issue with bauh?
Or should I just follow the suggestions from the article to rebuild Python packages?

**Comment by vinifmor** [comment]
Hi @kpspu , please, launch bauh through the command line (`bauh`) and post here any error stack.

**Comment by FuzzyMistborn** [comment]
Having the same issue, here's my error:
```
$ bauh
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 702, in _finish_refresh_packages
    if self.update_pkgs(res['installed'], as_installed=as_installed, types=res['types']):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 964, in update_pkgs
    self._update_table(pkgs_info=pkgs_info)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 842, in _update_table
    self._resize(accept_lower_width=len(self.pkgs) > 0)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 1079, in _resize
    self.resize(new_width, self.height())
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
Fatal Python error: Aborted

Thread 0x00007f4bb6ffd640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/thread.py", line 822 in run

Thread 0x00007f4bb5ffb640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007f4bf0dab640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/util/cache.py", line 96 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f4c0aa7f740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/app.py", line 57 in main
  File "/usr/bin/bauh", line 33 in <module>

Extension modules: _cffi_backend, PyQt5.QtCore, yaml._yaml, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork, cchardet._cchardet, lxml._elementpath, lxml.etree (total: 9)
zsh: abort (core dumped)  bauh
```

**Comment by Kandelai** [comment]
After the Python updates yesterday, Bauh on two of my systems (running Garuda/Arch linux) would start, then during the update process during the startup, would die each time. I even tried uninstalling/reinstalling, same. I assume it is affected like several apps with the Python 3.10 upgrade. More on this here;

[PSA: Python 3.10 is in [core]. Rebuild your AUR packages. - r/archlinux](https://libreddit.spike.codes/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/)

**Comment by vinifmor** [comment]
It is related to Qt signatures. I'm going to have a look here.

**Comment by vinifmor** [comment]
Since Python has been upgraded you have to reinstall **bauh**. These Qt signatures issues have already been fixed on the staging branch. Install **bauh-staging** from AUR and let me know if the crash doesn't happen.

**Comment by Kandelai** [comment]
I have rebuilt bauh, even using the staging version in AUR and I am still getting Python errors;

Icon theme "gnome" not found.
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 702, in _finish_refresh_packages
if self.update_pkgs(res['installed'], as_installed=as_installed, types=res['types']):
File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 964, in update_pkgs
self._update_table(pkgs_info=pkgs_info)
File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 842, in _update_table
self._resize(accept_lower_width=len(self.pkgs) > 0)
File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 1079, in _resize
self.resize(new_width, self.height())
TypeError: arguments did not match any overloaded call:
resize(self, QSize): argument 1 has unexpected type 'float'
resize(self, int, int): argument 1 has unexpected type 'float'
Fatal Python error: Aborted

Thread 0x00007f6b477fe640 (most recent call first):
File "/usr/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007f6b727fc640 (most recent call first):
File "/usr/lib/python3.10/site-packages/bauh/view/qt/thread.py", line 822 in run

Thread 0x00007f6b737fe640 (most recent call first):
File "/usr/lib/python3.10/site-packages/bauh/view/util/cache.py", line 96 in run
File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f6b9c698740 (most recent call first):
File "/usr/lib/python3.10/site-packages/bauh/app.py", line 57 in main
File "/usr/bin/bauh", line 33 in <module>

Extension modules: _cffi_backend, PyQt5.QtCore, yaml._yaml, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork, cchardet._cchardet, lxml._elementpath, lxml.etree (total: 9)
fish: Job 1, 'bauh' terminated by signal SIGABRT (Abort)

**Comment by Kandelai** [comment]
Disregard my last post, bauh-staging works. I hit the wrong version to install. The standard version though does not and gets the errors above. thx.

**Comment by Kandelai** [comment]
Thank you. I can't live without bauh. LOL

**Comment by vinifmor** [comment]
No worries. If any issue pops up on the **staging** branch, open a new issue, please.
