### ISSUE TITLE
bauh crashes with TypeError

### ISSUE THREAD

**Issue by mamrhein** [vinifmor/bauh#219]
On Arch, after having done some updates, bauh crashes on calling PyQt5 for resizing the window:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 702, in _finish_refresh_packages
    if self.update_pkgs(res['installed'], as_installed=as_installed, types=res['types']):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 964, in update_pkgs
    self._update_table(pkgs_info=pkgs_info)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 842, in _update_table
    self._resize(accept_lower_width=len(self.pkgs) > 0)
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/window.py", line 1079, in _resize
    self.resize(new_width, self.height())
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
Fatal Python error: Aborted

Thread 0x00007f4783fff640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/thread.py", line 822 in run

Thread 0x00007f47a0ff9640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007f47ccff9640 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/view/util/cache.py", line 96 in run
  File "/usr/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/usr/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f480e329740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/bauh/app.py", line 57 in main
  File "/usr/bin/bauh", line 33 in <module>

Extension modules: PyQt5.QtCore, yaml._yaml, PyQt5.QtGui, PyQt5.QtWidgets, PyQt5.QtNetwork (total: 5)
```
Installed versions:
bauh 0.9.23-1
python-pyqt5 5.15.6-6 (pyqt5)
python-pyqt5-sip 12.9.0-3

**Comment by vinifmor** [comment]
@mamrhein this issue is already fixed on the **staging** branch. Install **bauh-staging** from AUR and let me know if the issue has gone.

**Comment by Locutus64** [comment]
Switching to staging here works perfectly.

**Comment by mamrhein** [comment]
Yes, it is fixed in staging.

**Comment by vinifmor** [comment]
guys, the final **0.9.24** release is out
