### ISSUE TITLE
Clicking on the "?" for a Debian package causes infinite "Retrieving information" (and outright crashes on staging)

### ISSUE THREAD

**Issue by Templayer** [vinifmor/bauh#251]
**Describe the bug**
bauh has been stuck on this for like 20 minutes now:

![image](https://user-images.githubusercontent.com/11728067/161489745-547485fb-7003-4243-9fe7-ec8afb6f028b.png)

Duplication notes:

I'm trying to install CopyQ. The reason why the flatpack version of it is selected is that I've used the "?" button first to find out more information about it first (like the last update date). Then I've tried using the "?" for its Debian variant.

I'm going to test the staging version now by using the commands provided in the bug reporting template... OK, there it just crashed without an error when clicking on the "?" button for the Debian version of CopyQ. Nasty.

I can't find the file with logs for bauh. Where is that file located?

**Software Environment**
bauh version: 0.10.1
O.S: Linux Mint 20.3 Una with Cinnamon; kernel: 5.4.0-107-generic
Python version: Python 3.8.10
Installation method: pip3

**Comment by vinifmor** [comment]
Log files are only available for transaction operations (install, uninstall, ...). For the info dialog you can launch bauh though a CLI with the parameter `--logs`.

**Comment by Templayer** [comment]
Try catches are your friend, at least in Java. :P

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/bauh/view/qt/thread.py", line 669, in run
>     pkg_info = self.manager.get_info(self.pkg.model)
>   File "/usr/local/lib/python3.8/dist-packages/bauh/view/core/controller.py", line 360, in get_info
>     return man.get_info(app)
>   File "/usr/local/lib/python3.8/dist-packages/bauh/gems/debian/controller.py", line 344, in get_info
>     extra_info = self.aptitude.show((f'{pkg.name}={pkg.version}',), verbose=True)
>   File "/usr/local/lib/python3.8/dist-packages/bauh/gems/debian/aptitude.py", line 74, in show
>     number = float(size_split[0].replace(',', '.'))
> ValueError: could not convert string to float: '5???192'

**Comment by Templayer** [comment]
Basically, any button clicking / interaction with the user should be inside a broad try-catch block for any exception so that the application doesn't crash or hang when the user does an action. Like it does here.

With a message of something like "An error has occured - " + {errorMessage with error/exception name} + line break + "More details can be found inside log " + {logName and location}.

The log thus made would contain the error / exception name, error message and stacktrace.

**Comment by vinifmor** [comment]
Please, paste the output of the following commands:

1) `cat /etc/default/locale`
2) `aptitude show -q copyq -v`
3) `LANG='' aptitude show -q copyq -v`

**Comment by Templayer** [comment]
```
jboksa1@JB-PC:~$ cat /etc/default/locale
LANG=cs_CZ.UTF-8
LANGUAGE=cs_CZ:cs
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_MONETARY=cs_CZ.UTF-8
LC_PAPER=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
jboksa1@JB-PC:~$ aptitude show -q copyq -v
Balík: copyq
Verze: 3.10.0-1
Stav: nenainstalovaný
Priorita: volitelný
Sekce: universe/utils
Správce: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architektura: amd64
Velikost po rozbalení: 5 192 k
Komprimovaná velikost: 1 321 k
Název souboru: pool/universe/c/copyq/copyq_3.10.0-1_amd64.deb
Checksum-FileSize: 1321076
MD5Sum: ddd9b15aff1f58a2cdfd401b01e1dddf
SHA1: f3307fbd917ade85843ae28d165faa5bd218088e
SHA256: 3682df9bf32fd46137d6474b1c4dcb392ff9f652939423c8a23476d8fdc2c4b3
Archiv: focal
Závisí na: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2),
           libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1),
           libqt5network5 (>= 5.0.2), libqt5script5 (>= 5.6.0~beta), libqt5svg5
           (>= 5.6.0~beta), libqt5widgets5 (>= 5.11.0~rc1), libqt5x11extras5 (>=
           5.6.0), libstdc++6 (>= 4.8), libx11-6, libxtst6
Doporučuje: copyq-plugins (= 3.10.0-1)
Navrhuje: copyq-doc
Popis: Advanced clipboard manager with editing and scripting features
 CopyQ monitors system clipboard and saves its content in customized tabs. Saved
 clipboard can be later copied and pasted directly into any application. 
 
 Items can be: 
 * edited with internal editor or with preferred text editor, 
 * moved to other tabs, 
 * drag'n'dropped to applications, 
 * marked with tag or a note, 
 * passed to or changed by custom commands, 
 * or simply removed. 
   
 Features: 
 * Support for Linux, Windows and OS X 10.9+ 
 * Store text, HTML, images or any other custom formats 
 * Quickly browse and filter items in clipboard history 
 * Sort, create, edit, remove, copy/paste, drag'n'drop items in tabs 
 * Add notes or tags to items 
 * System-wide shortcuts with customizable commands 
 * Paste items with shortcut or from tray or main window 
 * Fully customizable appearance 
 * Advanced command-line interface and scripting 
 * Ignore clipboard copied from some windows or containing some text 
 * Support for simple Vim-like editor and shortcuts 
 * Many more features
Domovská stránka: https://hluk.github.io/CopyQ/


jboksa1@JB-PC:~$ LANG='' aptitude show -q copyq -v
Package: copyq
Version: 3.10.0-1
State: not installed
Priority: optional
Section: universe/utils
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 5???192 k
Compressed Size: 1???321 k
Filename: pool/universe/c/copyq/copyq_3.10.0-1_amd64.deb
Checksum-FileSize: 1321076
MD5Sum: ddd9b15aff1f58a2cdfd401b01e1dddf
SHA1: f3307fbd917ade85843ae28d165faa5bd218088e
SHA256: 3682df9bf32fd46137d6474b1c4dcb392ff9f652939423c8a23476d8fdc2c4b3
Archive: focal
Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1),
         libqt5network5 (>= 5.0.2), libqt5script5 (>= 5.6.0~beta), libqt5svg5 (>= 5.6.0~beta), libqt5widgets5 (>= 5.11.0~rc1),
         libqt5x11extras5 (>= 5.6.0), libstdc++6 (>= 4.8), libx11-6, libxtst6
Recommends: copyq-plugins (= 3.10.0-1)
Suggests: copyq-doc
Description: Advanced clipboard manager with editing and scripting features
 CopyQ monitors system clipboard and saves its content in customized tabs. Saved clipboard can be later copied and pasted directly into
 any application. 
 
 Items can be: 
 * edited with internal editor or with preferred text editor, 
 * moved to other tabs, 
 * drag'n'dropped to applications, 
 * marked with tag or a note, 
 * passed to or changed by custom commands, 
 * or simply removed. 
   
 Features: 
 * Support for Linux, Windows and OS X 10.9+ 
 * Store text, HTML, images or any other custom formats 
 * Quickly browse and filter items in clipboard history 
 * Sort, create, edit, remove, copy/paste, drag'n'drop items in tabs 
 * Add notes or tags to items 
 * System-wide shortcuts with customizable commands 
 * Paste items with shortcut or from tray or main window 
 * Fully customizable appearance 
 * Advanced command-line interface and scripting 
 * Ignore clipboard copied from some windows or containing some text 
 * Support for simple Vim-like editor and shortcuts 
 * Many more features
Homepage: https://hluk.github.io/CopyQ/

```

**Comment by Templayer** [comment]
LC_NUMERIC='' aptitude show -q copyq -v
Balík: copyq
Verze: 3.10.0-1
Stav: nenainstalovaný
Priorita: volitelný
Sekce: universe/utils
Správce: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architektura: amd64
Velikost po rozbalení: 5 192 k
Komprimovaná velikost: 1 321 k
Název souboru: pool/universe/c/copyq/copyq_3.10.0-1_amd64.deb
Checksum-FileSize: 1321076
MD5Sum: ddd9b15aff1f58a2cdfd401b01e1dddf
SHA1: f3307fbd917ade85843ae28d165faa5bd218088e
SHA256: 3682df9bf32fd46137d6474b1c4dcb392ff9f652939423c8a23476d8fdc2c4b3
Archiv: focal
Závisí na: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2),
           libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1),
           libqt5network5 (>= 5.0.2), libqt5script5 (>= 5.6.0~beta), libqt5svg5
           (>= 5.6.0~beta), libqt5widgets5 (>= 5.11.0~rc1), libqt5x11extras5 (>=
           5.6.0), libstdc++6 (>= 4.8), libx11-6, libxtst6
Doporučuje: copyq-plugins (= 3.10.0-1)
Navrhuje: copyq-doc
Popis: Advanced clipboard manager with editing and scripting features
 CopyQ monitors system clipboard and saves its content in customized tabs. Saved
 clipboard can be later copied and pasted directly into any application. 
 
 Items can be: 
 * edited with internal editor or with preferred text editor, 
 * moved to other tabs, 
 * drag'n'dropped to applications, 
 * marked with tag or a note, 
 * passed to or changed by custom commands, 
 * or simply removed. 
   
 Features: 
 * Support for Linux, Windows and OS X 10.9+ 
 * Store text, HTML, images or any other custom formats 
 * Quickly browse and filter items in clipboard history 
 * Sort, create, edit, remove, copy/paste, drag'n'drop items in tabs 
 * Add notes or tags to items 
 * System-wide shortcuts with customizable commands 
 * Paste items with shortcut or from tray or main window 
 * Fully customizable appearance 
 * Advanced command-line interface and scripting 
 * Ignore clipboard copied from some windows or containing some text 
 * Support for simple Vim-like editor and shortcuts 
 * Many more features
Domovská stránka: https://hluk.github.io/CopyQ/

**Comment by vinifmor** [comment]
Thank you for the feedback. So the initial info error you mentioned is fixed. 

This '{a}' is part of the aptitude output. It means additional package to be installed.

The bad number encoding in the install output would fit as another issue. But don't bother to open a new one, because I'm going to attach the same encoding fix for all the aptitude calls.

**Comment by Templayer** [comment]
> So the initial info error you mentioned is fixed.

Yeap!

> This '{a}' is part of the aptitude output. It means additional package to be installed.

Oh. Now I'm glad I've said "Unless that is correct." after that. Covering my arse from sounding completely stupid. :P  

> The bad number encoding in the install output would fit as another issue. But don't bother to open a new one, because I'm going to attach the same encoding fix for all the aptitude calls.

OK. If it is about Unicode encoding - maybe we should connect those issues somehow (with the one about Unicode encoding that has already been closed), or add that as a comment to there? Wait, does GitHub support linking Issues? Because GitLab does. :P

**Comment by vinifmor** [comment]
Sure... That's a good idea. I'm going to open a general encoding issue and link the related ones. By the way, I've published a fix to the output of the common transactions (install, uninstall, upgrade: https://github.com/vinifmor/bauh/archive/8cea0318ac23e31a8d141edc9512d42ff06ac350.tar.gz

**Comment by Templayer** [comment]
Seems to be working correctly for Debian... well, actually, no - it looks like the wrong part got outright skipped:

```
sudo -S aptitude install -q -y --no-gui --full-resolver copyq -o Aptitude::ProblemResolver::RemoveScore=9999999 -o Aptitude::ProblemResolver::EssentialRemoveScore=9999999

Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
The following NEW packages will be installed:
copyq copyq-plugins{a} libqt5script5{a}
0 packages upgraded, 3 newly installed, 0 to remove and 10 not upgraded.
Need to get 0 B/2547 kB of archives. After unpacking 10.2 MB will be used.
Writing extended state information...
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libqt5script5:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 417576 files and directories currently installed.)
Preparing to unpack .../libqt5script5_5.12.8+dfsg-0ubuntu1_amd64.deb ...
Unpacking libqt5script5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Selecting previously unselected package copyq.
Preparing to unpack .../copyq_3.10.0-1_amd64.deb ...
Unpacking copyq (3.10.0-1) ...
Selecting previously unselected package copyq-plugins.
Preparing to unpack .../copyq-plugins_3.10.0-1_amd64.deb ...
Unpacking copyq-plugins (3.10.0-1) ...
Setting up libqt5script5:amd64 (5.12.8+dfsg-0ubuntu1) ...
Setting up copyq (3.10.0-1) ...
Setting up copyq-plugins (3.10.0-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
Updating the apps index...
Installation logs can be found at "/tmp/bauh@jboksa1/logs/install/debian/copyq/1649402102.log"
```

**Comment by vinifmor** [comment]
The numbers seem to look fine -> `Need to get 0 B/2547 kB of archives. After unpacking 10.2 MB will be used.`

**Comment by Templayer** [comment]
But those weren't the really broken ones originally, as they read like this:

> Need to get 2 547 kB of archives. After unpacking 10,2 MB will be used.

**Comment by vinifmor** [comment]
Ah, they didn't appear because the packages are cached. They were downloaded the first time.

**Comment by Templayer** [comment]
I thought that as well. I guess I will have to check with a random package and hope for the best...

Yup, decimal separators are now there. Correctly. I presume these can be changed if locale is changed (I'm still planning to make a Czech version someday)?

```
sudo -S aptitude install -q -y --no-gui --full-resolver apache2 -o Aptitude::ProblemResolver::RemoveScore=9999999 -o Aptitude::ProblemResolver::EssentialRemoveScore=9999999

Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
The following NEW packages will be installed:
apache2 apache2-bin{a} apache2-data{a} apache2-utils{a} libapr1{a} libaprutil1{a} libaprutil1-dbd-sqlite3{a} libaprutil1-ldap{a}
0 packages upgraded, 8 newly installed, 0 to remove and 10 not upgraded.
Need to get 1715 kB of archives. After unpacking 7504 kB will be used.
Writing extended state information...
Get: 1 http://archive.ubuntu.com/ubuntu focal/main amd64 libapr1 amd64 1.6.5-1ubuntu1 [91.4 kB]
Get: 2 http://archive.ubuntu.com/ubuntu focal/main amd64 libaprutil1 amd64 1.6.1-4ubuntu2 [84.7 kB]
Get: 3 http://archive.ubuntu.com/ubuntu focal/main amd64 libaprutil1-dbd-sqlite3 amd64 1.6.1-4ubuntu2 [10.5 kB]
Get: 4 http://archive.ubuntu.com/ubuntu focal/main amd64 libaprutil1-ldap amd64 1.6.1-4ubuntu2 [8736 B]
Get: 5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apache2-bin amd64 2.4.41-4ubuntu3.10 [1181 kB]
Get: 6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apache2-data all 2.4.41-4ubuntu3.10 [158 kB]
Get: 7 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apache2-utils amd64 2.4.41-4ubuntu3.10 [84.5 kB]
Get: 8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apache2 amd64 2.4.41-4ubuntu3.10 [95.5 kB]
Fetched 1715 kB in 2s (717 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libapr1:amd64.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 417600 files and directories currently installed.)
Preparing to unpack .../0-libapr1_1.6.5-1ubuntu1_amd64.deb ...
Unpacking libapr1:amd64 (1.6.5-1ubuntu1) ...
Selecting previously unselected package libaprutil1:amd64.
Preparing to unpack .../1-libaprutil1_1.6.1-4ubuntu2_amd64.deb ...
Unpacking libaprutil1:amd64 (1.6.1-4ubuntu2) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack .../2-libaprutil1-dbd-sqlite3_1.6.1-4ubuntu2_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.6.1-4ubuntu2) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../3-libaprutil1-ldap_1.6.1-4ubuntu2_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.6.1-4ubuntu2) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../4-apache2-bin_2.4.41-4ubuntu3.10_amd64.deb ...
Unpacking apache2-bin (2.4.41-4ubuntu3.10) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../5-apache2-data_2.4.41-4ubuntu3.10_all.deb ...
Unpacking apache2-data (2.4.41-4ubuntu3.10) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../6-apache2-utils_2.4.41-4ubuntu3.10_amd64.deb ...
Unpacking apache2-utils (2.4.41-4ubuntu3.10) ...
Selecting previously unselected package apache2.
Preparing to unpack .../7-apache2_2.4.41-4ubuntu3.10_amd64.deb ...
Unpacking apache2 (2.4.41-4ubuntu3.10) ...
Setting up libapr1:amd64 (1.6.5-1ubuntu1) ...
Setting up apache2-data (2.4.41-4ubuntu3.10) ...
Setting up libaprutil1:amd64 (1.6.1-4ubuntu2) ...
Setting up libaprutil1-ldap:amd64 (1.6.1-4ubuntu2) ...
Setting up libaprutil1-dbd-sqlite3:amd64 (1.6.1-4ubuntu2) ...
Setting up apache2-utils (2.4.41-4ubuntu3.10) ...
Setting up apache2-bin (2.4.41-4ubuntu3.10) ...
Setting up apache2 (2.4.41-4ubuntu3.10) ...
Enabling module mpm_event.
Enabling module authz_core.
Enabling module authz_host.
Enabling module authn_core.
Enabling module auth_basic.
Enabling module access_compat.
Enabling module authn_file.
Enabling module authz_user.
Enabling module alias.
Enabling module dir.
Enabling module autoindex.
Enabling module env.
Enabling module mime.
Enabling module negotiation.
Enabling module setenvif.
Enabling module filter.
Enabling module deflate.
Enabling module status.
Enabling module reqtimeout.
Enabling conf charset.
Enabling conf localized-error-pages.
Enabling conf other-vhosts-access-log.
Enabling conf security.
Enabling conf serve-cgi-bin.
Enabling site 000-default.
Created symlink /etc/systemd/system/multi-user.target.wants/apache2.service -> /lib/systemd/system/apache2.service.
Created symlink /etc/systemd/system/multi-user.target.wants/apache-htcacheclean.service -> /lib/systemd/system/apache-htcacheclean.service.
Processing triggers for ufw (0.36-6ubuntu1) ...
Pravidla aktualizována pro profil 'Samba'
Processing triggers for systemd (245.4-4ubuntu3.15) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.7) ...
Reading package lists...
Building dependency tree...
Reading state information...
Reading extended state information...
Initializing package states...
Writing extended state information...
Building tag database...
Updating the apps index...
Installation logs can be found at "/tmp/bauh@jboksa1/logs/install/debian/apache2/1649424058.log"
```

**Comment by vinifmor** [comment]
Actually the main operations are generally executed in English because bauh needs to understand the output to handle common errors. Otherwise we would need a handler for each language in the world.

A Czech translation would be welcome :)
