### ISSUE TITLE
can't start bauh, after click on (Anwendungen in german) Apps the terminal shows:

### ISSUE THREAD

**Issue by LinuxOpa** [vinifmor/bauh#307]
**Describe the bug**
bauh-tray, click on Apps (Anwendungen), in Terminal startet.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/bauh/app.py", line 75, in <module>
    main()
  File "/home/user/.local/lib/python3.8/site-packages/bauh/app.py", line 64, in main
    app, widget = new_manage_panel(args, app_config, logger)
  File "/home/user/.local/lib/python3.8/site-packages/bauh/manage.py", line 55, in new_manage_panel
    managers = gems.load_managers(context=context, locale=i18n.current_key, config=app_config,
  File "/home/user/.local/lib/python3.8/site-packages/bauh/view/core/gems.py", line 55, in load_managers
    module = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.local/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 45, in <module>
    from bauh.gems.arch.dependencies import DependenciesAnalyser
  File "/home/user/.local/lib/python3.8/site-packages/bauh/gems/arch/dependencies.py", line 11, in <module>
    from bauh.gems.arch.version import match_required_version
  File "/home/user/.local/lib/python3.8/site-packages/bauh/gems/arch/version.py", line 3, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/user/.local/lib/python3.8/site-packages/packaging/version.py)

**Software Environment**
bauh version: 0.10.4
O.S: ubuntu 20.04.lts actual
Python version: pip 22.3.1 python3.8
Installation method: pip

with your installation routine, bauh 0.10.5:
bauh-tray, click on Apps (Anwendungen), in Terminal startet.
venv/bin/bauh-tray
Traceback (most recent call last):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 552, in run
    success = bool(self.manager.upgrade(requirements, root_password, self))
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/core/controller.py", line 297, in upgrade
    res = man.upgrade(man_reqs, root_password, handler)
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 384, in upgrade
    if not self._install(pkg=req.pkg, watcher=watcher, pre_downloaded_file=download_data).success:
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 598, in _install
    downloaded, file_name = True, pkg.local_file_path.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
Fatal Python error: Aborted

Current thread 0x00007f491bfff700 (most recent call first):
<no Python frame>

Thread 0x00007f491affd700 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 844 in run

Thread 0x00007f49288c7700 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/gems/snap/snap.py", line 59 in is_api_available
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/gems/snap/controller.py", line 314 in list_warnings
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/core/controller.py", line 475 in list_warnings
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 933 in run

Thread 0x00007f49290c8700 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/qt/thread.py", line 844 in run

Thread 0x00007f4918ff9700 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/qt/prepare.py", line 140 in run

Thread 0x00007f49298c9700 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/view/util/cache.py", line 96 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f4968e09740 (most recent call first):
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/app.py", line 67 in main
  File "/home/user/Downloads/x/bauh/venv/lib/python3.8/site-packages/bauh/app.py", line 75 in <module>

**Comment by LinuxOpa** [comment]
staring the AppImage:
./bauh-0.10.4-x86_64.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_bauh-0HSAuvZ//usr/bin/bauh", line 8, in <module>
    sys.exit(main())
  File "/tmp/.mount_bauh-0HSAuvZ/usr/lib/python3.8/site-packages/bauh/app.py", line 64, in main
    app, widget = new_manage_panel(args, app_config, logger)
  File "/tmp/.mount_bauh-0HSAuvZ/usr/lib/python3.8/site-packages/bauh/manage.py", line 55, in new_manage_panel
    managers = gems.load_managers(context=context, locale=i18n.current_key, config=app_config,
  File "/tmp/.mount_bauh-0HSAuvZ/usr/lib/python3.8/site-packages/bauh/view/core/gems.py", line 55, in load_managers
    module = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/.mount_bauh-0HSAuvZ/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 14, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/db/.local/lib/python3.8/site-packages/packaging/version.py)
