### ISSUE TITLE
bauh does not start anymoe

### ISSUE THREAD

**Issue by Mape6** [vinifmor/bauh#325]
**Describe the bug**
Here is the log of the journal
```
Mai 05 10:09:15 PC plasmashell[886]: QString::arg: 2 argument(s) missing in bauh
Mai 05 10:09:15 PC systemd[690]: Started Anwendungen (bauh).
Mai 05 10:09:15 PC plasmashell[46889]: Traceback (most recent call last):
Mai 05 10:09:15 PC plasmashell[46889]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
Mai 05 10:09:15 PC plasmashell[46889]:     return next(cls.discover(name=name))
Mai 05 10:09:15 PC plasmashell[46889]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mai 05 10:09:15 PC plasmashell[46889]: StopIteration
Mai 05 10:09:15 PC plasmashell[46889]: During handling of the above exception, another exception occurred:
Mai 05 10:09:15 PC plasmashell[46889]: Traceback (most recent call last):
Mai 05 10:09:15 PC plasmashell[46889]:   File "/usr/bin/bauh", line 33, in <module>
Mai 05 10:09:15 PC plasmashell[46889]:     sys.exit(load_entry_point('bauh==0.10.5', 'console_scripts', 'bauh')())
Mai 05 10:09:15 PC plasmashell[46889]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mai 05 10:09:15 PC plasmashell[46889]:   File "/usr/bin/bauh", line 22, in importlib_load_entry_point
Mai 05 10:09:15 PC plasmashell[46889]:     for entry_point in distribution(dist_name).entry_points
Mai 05 10:09:15 PC plasmashell[46889]:                        ^^^^^^^^^^^^^^^^^^^^^^^
Mai 05 10:09:15 PC plasmashell[46889]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
Mai 05 10:09:15 PC plasmashell[46889]:     return Distribution.from_name(distribution_name)
Mai 05 10:09:15 PC plasmashell[46889]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mai 05 10:09:15 PC plasmashell[46889]:   File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
Mai 05 10:09:15 PC plasmashell[46889]:     raise PackageNotFoundError(name)
Mai 05 10:09:15 PC plasmashell[46889]: importlib.metadata.PackageNotFoundError: No package metadata was found for bauh
```

**Software Environment**
bauh version: 0.10.5-1
O.S: EndeavourOS Kernel 6.3.1-arch1-1
Python version: Python 3.11.3
Installation method: AUR

**Comment by vinifmor** [comment]
Hello @Mape6 , since Arch has upgraded Python from 3.10 to 3.11, you'll need to reinstall bauh.

**Comment by keilmillerjr** [comment]
> Hello @Mape6 , since Arch has upgraded Python from 3.10 to 3.11, you'll need to reinstall bauh.

I can confirm this error after python update. Reinstalling bauh did indeed resolve the issue. Thank you @Mape6.

**Comment by vinifmor** [comment]
No worries, folks

**Comment by pmslava** [comment]
Yes, agree. A clean build helped me.
