### ISSUE TITLE
Crashes with KeyError: 'grub'

### ISSUE THREAD

**Issue by specs32** [vinifmor/bauh#329]
I use a freshly updated endeavourOS 
Installed and tried both aur versions and the manual compile from source like in the issue description
python version is shown in the error message..
happens on every start of the binary.
keeps looping until I skip it... then works.
did no further tests.
 Have a nice day !

PS: FYI grub is downgraded on my system and on the ignore list in /etc/pacman.conf  ;)
`cat /etc/pacman.conf |grep -ie  ignore
IgnorePkg = grub

`

´

$ venv/bin/bauh
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/happybum/src/bauh/venv/lib/python3.11/site-packages/bauh/gems/arch/worker.py", line 227, in run
    installed = self.controller.read_installed(disk_loader=None, internet_available=self.internet_available,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/happybum/src/bauh/venv/lib/python3.11/site-packages/bauh/gems/arch/controller.py", line 589, in read_installed
    installed = pacman.map_packages(names=names)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/happybum/src/bauh/venv/lib/python3.11/site-packages/bauh/gems/arch/pacman.py", line 157, in map_packages
    del pkgs[key][pkg]
        ~~~~~~~~~^^^^^
KeyError: 'grub'
´

**Comment by vinifmor** [comment]
Hi @specs32 , I'll have a look here... thank you for reporting the issue

**Comment by vinifmor** [comment]
The fix is available in the staging branch
