### ISSUE TITLE
AppImage on Debian Stretch

### ISSUE THREAD

**Issue by antoninchadima** [vinifmor/bauh#46]
I'm unable to get AppImage support on Debian

I get this error and the appimage does not download even if it exists on the given adress:
Traceback (most recent call last):

```
  File "/usr/local/lib/python3.5/dist-packages/bauh/view/core/downloader.py", line 85, in download
    process = self._get_aria2c_process(file_url, output_path, final_cwd)
  File "/usr/local/lib/python3.5/dist-packages/bauh/view/core/downloader.py", line 46, in _get_aria2c_process
    return SystemProcess(new_subprocess(cmd=cmd, cwd=cwd),
  File "/usr/local/lib/python3.5/dist-packages/bauh/commons/system.py", line 210, in new_subprocess
    return subprocess.Popen(cmd, **args)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1221, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'PosixPath' object to str implicitly
```

**Comment by antoninchadima** [comment]
It is something around pathlib not being a string.
But i'm not good in python...

**Comment by vinifmor** [comment]
Hi @antoninchadima , thank you for reporting the issue. I will try to reproduce here.

**Comment by vinifmor** [comment]
It seems to be a Python3.5 issue. I pushed a possible fix on the **staging** branch. Could you give a feedback if it works now ?

**Comment by antoninchadima** [comment]
Thank you very much. It is working now. 
It was really a Python 3.5 issue (Debian 9 Stretch [with backports] on Chrome OS...)

I though even before your answer, that it has to do something with the Python version (the difference between Arch and Debian 9)...
