### ISSUE TITLE
fre:ac AppImage installs aarch64 instead of x86_64

### ISSUE THREAD

**Issue by canihavesomecoffee** [vinifmor/bauh#60]
I'm attempting to install the fre:ac application using the GUI of bauh.

fre:ac is listed as an AppImage, but when I try to install, it retrieves the aarch64 version of the AppImage from GitHub instead of the x86_64. Of course this fails to execute on my system before the installation finishes.

Relevant log which I retrieved from `/tmp/bauh/web/install/fre:ac/`:

```
wget https://github.com/enzo1982/freac/releases/download/continuous/freac-continuous-linux-aarch64.AppImage --continue --retry-connrefused --tries=10 --no-config -O /home/user/.local/share/bauh/appimage/installed/fre:ac/freac-continuous-linux-aarch64.AppImage

--2020-02-16 17:39:29--  https://github.com/enzo1982/freac/releases/download/continuous/freac-continuous-linux-aarch64.AppImage
{snipped for brevity}
14650K .......... .........                                  100%  186M=1.2s
2020-02-16 17:39:31 (11.7 MB/s) - '/home/user/.local/share/bauh/appimage/installed/fre:ac/freac-continuous-linux-aarch64.AppImage' saved [15021232/15021232]

chmod a+x /home/user/.local/share/bauh/appimage/installed/fre:ac/freac-continuous-linux-aarch64.AppImage

rm -rf /home/user/.local/share/bauh/appimage/installed/fre:ac
```

The error that pops up in the GUI is as follows:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/gems/appimage/controller.py", line 314, in install
    res, output = handler.handle_simple(SimpleProcess([file_path, '--appimage-extract'], cwd=out_dir))
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 77, in __init__
    self.instance = self._new(final_cmd, cwd, global_interpreter, lang, stdin=pwdin, extra_paths=extra_paths)
  File "/usr/lib/python3.8/site-packages/bauh/commons/system.py", line 93, in _new
    return subprocess.Popen(cmd, **args)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/user/.local/share/bauh/appimage/installed/fre:ac/freac-continuous-linux-aarch64.AppImage'
```

If I manually download the x86_64 it works of course, but then it's not registered by bauh :(

Lastly I want to say I love this application :) Makes my life a ton easier :+1:

**Comment by vinifmor** [comment]
Hello @canihavesomecoffee , it is probably a bug with the script responsible to generate the bauh's AppImage database. I'm going to have a look here and fix ASAP. Thank you for reporting this issue.

**Comment by vinifmor** [comment]
@canihavesomecoffee , already fixed the script. Re-install **fre:ac** and let me know if it is working now.

**Comment by canihavesomecoffee** [comment]
@vinifmor It is fixed, thank you for the very quick reply! :tada:

**Comment by vinifmor** [comment]
No worries. I'm going to close this issue. Cheers.
