### ISSUE TITLE
Bauh not starting

### ISSUE THREAD

**Issue by szarik001** [vinifmor/bauh#84]
When I try to start bauh I get this error:
`Traceback (most recent call last):
  File "/usr/bin/bauh", line 11, in <module>
    load_entry_point('bauh==0.8.5', 'console_scripts', 'bauh')()
  File "/usr/lib/python3.8/site-packages/bauh/app.py", line 46, in main
    i18n_key, current_i18n = translation.get_locale_keys(local_config['locale'])
  File "/usr/lib/python3.8/site-packages/bauh/view/util/translation.py", line 64, in get_locale_keys
    if current_locale == name or current_locale.startswith(name + '_'):
AttributeError: 'NoneType' object has no attribute 'startswith'`
I installed bauh from the AUR and it didn't work. I then tried to install using pip with the same result

**Comment by szarik001** [comment]
I got it working by removing `or current_locale.startswith(name + '_')` on line 64 of /usr/lib/python3.8/site-packages/bauh/view/util/translation.py"

**Comment by szarik001** [comment]
Never mind. Bauh starts but cant install anything.

**Comment by vinifmor** [comment]
@szarik001 , could you paste the result o the following command (`python -c "import locale; print(locale.getdefaultlocale())"`) here ?

Also, when you say you can't install anything it means you cannot find any to install ?

**Comment by szarik001** [comment]
@vinifmor the command returns the following:
`(None, None)`

> Also, when you say you can't install anything it means you cannot find any to install ?

After changing translations.py as mentioned when I try to install an aur package it doesn't work. Here is the log:
```
sudo -S pacman -Syy

:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
downloading multilib.db...
downloading sublime-text.db...
downloading sublime-text.db.sig...
```

**Comment by vinifmor** [comment]
It seems your Python installation is not able to retrieve your system default locale. I'm going to add a workaround to use English for this scenario.

Open it through the command line (`bauh`) and see if any error output is displayed when you try to install the package you want. (by the way, which one are you trying to install ? I'm going to try it here )

**Comment by szarik001** [comment]
@vinifmor I'm trying to install proton-ge-custom-bin from the aur. I'm not currently at my PC but once I get back, I'll send you the command line output.

**Comment by vinifmor** [comment]
Ok, I will be waiting for you logs to see what's happening on your system. I've just installed with bauh **0.8.5** and had no issues.

![bauh_error_1](https://user-images.githubusercontent.com/4312414/79148936-b4358d00-7d9c-11ea-9ae6-cf44c955a988.png)

![bauh_error_2](https://user-images.githubusercontent.com/4312414/79148945-b8fa4100-7d9c-11ea-8b1e-e131f9d60423.png)

I've already fixed the locale issue. I will be publishing the fix to **bauh-staging** (AUR) in a few hours.

**Comment by szarik001** [comment]
I ran Bauh from the terminal and I tried installing it again. This is the output from the terminal:

```
 seb~$ bauh
qt5ct: using qt5ct plugin
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/worker.py", line 203, in run
    self.optimize()
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/worker.py", line 174, in optimize
    custom_makepkg = custom_makepkg + '\n' + generated_by + '\n'.join(optimizations) + '\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 4384, resource id: 10976517, major code: 40 (TranslateCoords), minor code: 0
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bauh/view/core/controller.py", line 251, in install
    return man.install(app, root_password, handler)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 939, in install
    res = self._install_from_aur(pkg.name, pkg.package_base, pkg.maintainer, root_password, handler, dependency=False, skip_optdeps=skip_optdeps)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 838, in _install_from_aur
    self._optimize_makepkg(watcher=handler.watcher)
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/controller.py", line 922, in _optimize_makepkg
    ArchCompilationOptimizer(self.context.logger).optimize()
  File "/usr/lib/python3.8/site-packages/bauh/gems/arch/worker.py", line 174, in optimize
    custom_makepkg = custom_makepkg + '\n' + generated_by + '\n'.join(optimizations) + '\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by vinifmor** [comment]
@szarik001, try **bauh-staging** (version 0.9.0.RC-3) from **AUR** and let me know if its working now.

**Comment by szarik001** [comment]
It got further then last time but still didn't install.
This is from the log file:
```
Package databases already synchronized
mkdir -p /tmp/bauh/arch/build_1586878808

wget https://aur.archlinux.org/cgit/aur.git/snapshot/proton-ge-custom-bin.tar.gz

--2020-04-14 16:40:08--  https://aur.archlinux.org/cgit/aur.git/snapshot/proton-ge-custom-bin.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving aur.archlinux.org (aur.archlinux.org)... 5.9.250.164, 2a01:4f8:160:3033::2
Connecting to aur.archlinux.org (aur.archlinux.org)|5.9.250.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'proton-ge-custom-bin.tar.gz'
0K ..........                                              286M=0s
2020-04-14 16:40:08 (286 MB/s) - 'proton-ge-custom-bin.tar.gz' saved [10474]
tar xvzf proton-ge-custom-bin.tar.gz

proton-ge-custom-bin/
proton-ge-custom-bin/.SRCINFO
proton-ge-custom-bin/PKGBUILD
proton-ge-custom-bin/changelog
proton-ge-custom-bin/supplementary.tar.zst
Custom optimized makepkg.conf ( /home/seb/.config/bauh/arch/makepkg.conf ) not found
makepkg -ALcf --check --noarchive --nobuild --noprepare --nodeps

==> Making package: proton-ge-custom-bin 5.6_GE_2-1 (Tue Apr 14 16:40:09 2020)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
-> Downloading proton-ge-custom-5.6-GE-2.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   635  100   635    0     0   4503      0 --:--:-- --:--:-- --:--:--  4471
0  395M    0  424k    0     0   394k      0  0:17:07  0:00:01  0:17:06  394k
  2  395M    2 10.5M    0     0  5311k      0  0:01:16  0:00:02  0:01:14 10.5M
  5  395M    5 21.4M    0     0  7264k      0  0:00:55  0:00:03  0:00:52 10.7M
  8  395M    8 32.3M    0     0  8243k      0  0:00:49  0:00:04  0:00:45 10.8M
 10  395M   10 43.2M    0     0  8831k      0  0:00:45  0:00:05  0:00:40 10.8M
 13  395M   13 54.1M    0     0  9226k      0  0:00:43  0:00:06  0:00:37 10.8M
 16  395M   16 65.0M    0     0  9510k      0  0:00:42  0:00:07  0:00:35 10.9M
 19  395M   19 75.9M    0     0  9723k      0  0:00:41  0:00:08  0:00:33 10.9M
 21  395M   21 86.8M    0     0  9844k      0  0:00:41  0:00:09  0:00:32 10.8M
 24  395M   24 97.7M    0     0  9976k      0  0:00:40  0:00:10  0:00:30 10.8M
 27  395M   27  108M    0     0   9.8M      0  0:00:40  0:00:11  0:00:29 10.8M
 30  395M   30  119M    0     0   9.9M      0  0:00:39  0:00:12  0:00:27 10.8M
 32  395M   32  130M    0     0  10.0M      0  0:00:39  0:00:13  0:00:26 10.8M
 35  395M   35  141M    0     0  10.0M      0  0:00:39  0:00:14  0:00:25 10.8M
 38  395M   38  151M    0     0  10.1M      0  0:00:39  0:00:15  0:00:24 10.9M
 41  395M   41  163M    0     0  10.1M      0  0:00:38  0:00:16  0:00:22 10.9M
 44  395M   44  174M    0     0  10.2M      0  0:00:38  0:00:17  0:00:21 11.0M
 46  395M   46  185M    0     0  10.3M      0  0:00:38  0:00:18  0:00:20 11.0M
 49  395M   49  196M    0     0  10.3M      0  0:00:38  0:00:19  0:00:19 11.1M
 52  395M   52  207M    0     0  10.3M      0  0:00:38  0:00:20  0:00:18 11.1M
 55  395M   55  218M    0     0  10.3M      0  0:00:38  0:00:21  0:00:17 11.0M
 57  395M   57  229M    0     0  10.4M      0  0:00:37  0:00:22  0:00:15 11.0M
 60  395M   60  240M    0     0  10.4M      0  0:00:37  0:00:23  0:00:14 10.9M
 63  395M   63  251M    0     0  10.4M      0  0:00:37  0:00:24  0:00:13 10.9M
 66  395M   66  262M    0     0  10.4M      0  0:00:37  0:00:25  0:00:12 10.8M
 68  395M   68  272M    0     0  10.4M      0  0:00:37  0:00:26  0:00:11 10.8M
 71  395M   71  283M    0     0  10.4M      0  0:00:37  0:00:27  0:00:10 10.8M
 74  395M   74  294M    0     0  10.5M      0  0:00:37  0:00:28  0:00:09 10.8M
 77  395M   77  305M    0     0  10.5M      0  0:00:37  0:00:29  0:00:08 10.8M
 79  395M   79  316M    0     0  10.5M      0  0:00:37  0:00:30  0:00:07 10.8M
 82  395M   82  327M    0     0  10.5M      0  0:00:37  0:00:31  0:00:06 10.9M
 85  395M   85  338M    0     0  10.5M      0  0:00:37  0:00:32  0:00:05 10.9M
 88  395M   88  349M    0     0  10.5M      0  0:00:37  0:00:33  0:00:04 10.9M
 91  395M   91  360M    0     0  10.5M      0  0:00:37  0:00:34  0:00:03 10.9M
 93  395M   93  370M    0     0  10.5M      0  0:00:37  0:00:35  0:00:02 10.9M
 96  395M   96  381M    0     0  10.6M      0  0:00:37  0:00:36  0:00:01 10.9M
 99  395M   99  392M    0     0  10.6M      0  0:00:37  0:00:37 --:--:-- 10.9M
100  395M  100  395M    0     0  10.6M      0  0:00:37  0:00:37 --:--:-- 10.9M
-> Found supplementary.tar.zst
==> Validating source files with md5sums...
proton-ge-custom-5.6-GE-2.tar.gz ... Passed
supplementary.tar.zst ... Passed
==> Extracting sources...
-> Extracting proton-ge-custom-5.6-GE-2.tar.gz with bsdtar
bsdtar: Failed to set default locale
-> Extracting supplementary.tar.zst with bsdtar
bsdtar: Failed to set default locale
==> Sources are ready.
Custom optimized makepkg.conf ( /home/seb/.config/bauh/arch/makepkg.conf ) not found
makepkg -ALcsmf --skipchecksums

==> Making package: proton-ge-custom-bin 5.6_GE_2-1 (Tue Apr 14 16:40:51 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found proton-ge-custom-5.6-GE-2.tar.gz
-> Found supplementary.tar.zst
==> WARNING: Skipping verification of source file checksums.
==> Extracting sources...
-> Extracting proton-ge-custom-5.6-GE-2.tar.gz with bsdtar
bsdtar: Failed to set default locale
-> Extracting supplementary.tar.zst with bsdtar
bsdtar: Failed to set default locale
==> Starting build()...
patching file Proton-5.6-GE-2/proton
Hunk #3 succeeded at 640 (offset 7 lines).
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
-> Removing libtool files...
-> Purging unwanted files...
-> Removing static library files...
-> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "proton-ge-custom-bin"...
-> Generating .PKGINFO file...
-> Generating .BUILDINFO file...
-> Adding changelog file...
-> Generating .MTREE file...
-> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: proton-ge-custom-bin 5.6_GE_2-1 (Tue Apr 14 16:41:05 2020)
==> Cleaning up...
Could not find generated .tar.xz file. Aborting...
rm -rf /tmp/bauh/arch/build_1586878808
```
And this is from the console:
```
qt5ct: using qt5ct plugin
which: no aria2c in (/usr/lib/python3.8:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin:/home/seb/.config:/home/seb/.local/bin:/home/seb/bin:/home/seb/Scripts)
```

**Comment by vinifmor** [comment]
Already know what's happening. I'm going to publish a fix to bauh-staging in a few hours

**Comment by vinifmor** [comment]
Could you paste the result of the following command here ? (`cat /etc/makepkg.conf | grep PKGEXT`)

**Comment by szarik001** [comment]
it returns `PKGEXT='.pkg.tar'`

**Comment by vinifmor** [comment]
please, edit this file (**/etc/makepkg.conf**) and replace the **PKGEXT** value by **'.pkg.tar.xz'**. Then try again to install the AUR packages you want. Give me a feedback if it works now.

**Comment by szarik001** [comment]
Thanks. That fixed it. It works fine now.

**Comment by vinifmor** [comment]
No worries. Cheers.
